### PR TITLE
update states changed

### PR DESCRIPTION
**Pull request by earth08**
this change is for state change,
some apps depends wake_locks_size
wake_locks_size == 1   is paused
wake_locks_size == 2   is playing
wake_locks_size == 0 is standby
wake_locks_size == -1 is idle

### CODE REVIEW

**Comment by JeffLIrion** [comment]
Thanks for the pull request!  But please submit this to the [state-detection](https://github.com/JeffLIrion/python-androidtv/tree/state-detection) branch, not the master branch.  

Also, `wake_lock_size` is -1 when `screen_on` is False or `awake` is False.  This is because when you run `get_properties(lazy=True)`, it won't proceed if the device is off or idle (aka in screensaver mode, aka `awake` is False).  I needed a value to assign to `wake_lock_size` and I chose -1 rather than `None` because that way I could still do numerical comparisons if I wanted.  In other words, `wake_lock_size` being -1 is a byproduct of other properties, not a true observed property.

**Comment by earth08** [comment]
Please let me know how to change it to state-detection branch?

**Comment by earth08** [comment]
scene off doesnt display
it sometime detects with the chages i made it doesnt change its status, it display the last state.
this are the output
2019-03-20 08:42:29 INFO (SyncWorker_17) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 4, 'media_session_state': None, 'current_app': {'package': 'off', 'activity': None}, 'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 1}
2019-03-20 08:42:29 INFO (SyncWorker_18) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 4, 'media_session_state': None, 'current_app': {'package': 'off', 'activity': None}, 'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 1}
2019-03-20 08:42:30 INFO (SyncWorker_9) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 3, 'media_session_state': None, 'current_app': {'package': 'off', 'activity': None}, 'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 1}

can we make some modification with package: off than shows off rather than wakelock for off

**Comment by JeffLIrion** [comment]
> Please let me know how to change it to state-detection branch?

The easiest thing to do is probably just to go to the [androidtv.py file on the state-detection branch](https://github.com/JeffLIrion/python-androidtv/blob/state-detection/androidtv/androidtv.py) and just make your changes there.

**Comment by JeffLIrion** [comment]
> scene off doesnt display
> it sometime detects with the chages i made it doesnt change its status, it display the last state.
> this are the output
> 2019-03-20 08:42:29 INFO (SyncWorker_17) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 4, 'media_session_state': None, 'current_app': {'package': 'off', 'activity': None}, 'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 1}
> 2019-03-20 08:42:29 INFO (SyncWorker_18) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 4, 'media_session_state': None, 'current_app': {'package': 'off', 'activity': None}, 'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 1}
> 2019-03-20 08:42:30 INFO (SyncWorker_9) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 3, 'media_session_state': None, 'current_app': {'package': 'off', 'activity': None}, 'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 1}
> 
> can we make some modification with package: off than shows off rather than wakelock for off

So when your device is off, it shows that the current app is "off" (as in, that is its app ID)?  But the `screen_on` and `awake` properties are both `True`?

**Comment by earth08** [comment]
Yes, 
But due to awake and screen on status
I am not getting status off as expected.
So is there any way to get status as off when current_app is off.
But I think it want stay long since when it is turned off it throws an error, already put that is new issue.

**Comment by JeffLIrion** [comment]
I made the changes.

**Pull request closed without merging**
