### PR TITLE
Add fast forward and rewind key codes

### PR DESCRIPTION
**Pull request by TheZoker**

### CODE REVIEW

**Comment by JeffLIrion** [comment]
Are these key codes the same for Android TV and Fire TV?

**Comment by TheZoker** [comment]
Yes they are from the android key code documentation and also work on fire tv (tested)

**Comment by JeffLIrion** [comment]
Can you put fast-forward after enter, please.

**Comment by TheZoker** [comment]
Done

**Comment by JeffLIrion** [comment]
Thanks!

**Pull request merged**
