### PR TITLE
fix amazon video state for fire 4k

### PR DESCRIPTION
**Pull request by lolouk44**
fix amazon video state for fire 4k

### CODE REVIEW

**Comment by JeffLIrion** [comment]
You need to update the tests. Please see this post for more info: https://github.com/JeffLIrion/python-androidtv/pull/152#issuecomment-587961353

**Comment by lolouk44** [comment]
closing and trying again with the tests ;)

**Comment by lolouk44** [comment]
> You need to update the tests. Please see this post for more info: [#152 (comment)](https://github.com/JeffLIrion/python-androidtv/pull/152#issuecomment-587961353)

I guess I need to update the tests for the _test_firetv.py_ file only? Or do I also need to update the file for _test_androidtv.py_?
Do I just update the _Amazon Video_ part or both _Amazon Video_  and _Amazon Video with custom state detection rules_?

**Comment by JeffLIrion** [comment]
Just the `test_state_detection` test in `test_firetv.py`. You don't need to close the pull request, you can make as many commits as you want until you get everything to pass. You should be able to see the log from the Travis CI build if you click on the link in the checks that show up for this pull request. For example: https://travis-ci.com/github/JeffLIrion/python-androidtv/jobs/325287830

**Pull request closed without merging**
