### PR TITLE
Added detection of Plex state

### PR DESCRIPTION
**Pull request by diosdog**
Plex doesn't correctly update the state detected by `dumpsys media_session` so use audio state instead.

### CODE REVIEW

**Comment by JeffLIrion** [comment]
My 2nd generation Fire TV stick doesn't have `sed`. 

```
2019-06-01 17:12:11 CRITICAL (SyncWorker_18) [custom_components.androidtv.media_player] Output of command 'dumpsys media_session | sed -n -e 'Sessions Stack'' from 'media_player.fire_tv_living_room': /system/bin/sh: sed: not found
```

**Comment by JeffLIrion** [comment]
For getting the media session state, you could do something like 

```
dumpsys media_session | grep -A 100 'Sessions Stack'
```

and then parse the result in the [`_media_session_state`](https://github.com/JeffLIrion/python-androidtv/blob/2bd73d105f48986b91d06c9d5fad5b044fda88b5/androidtv/basetv.py#L604) method, which would now require a second parameter `current_app`.

**Comment by diosdog** [comment]
Hmm, that's unfortunate that the Fire TV doesn't have `sed`. I did actually start by implementing something similar to what you suggest with the multiline grep result. However, the `get_properties` method calls a sequence of those adb commands expecting each to only return a single line. If handling the multiline parsing for media_session in Python then `get_properties` needs to be modified too.

**Comment by JeffLIrion** [comment]
Here's a one-liner to get the current app:

```
CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP##*u0 } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP
```

**Comment by JeffLIrion** [comment]
This might work:

```
CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP##*u0 } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {'
```

**Comment by JeffLIrion** [comment]
I think this is a little better:

```
CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {'
```

**Comment by diosdog** [comment]
Based on some quick testing on an Nvidia Shield, that works! Updated pull request.

**Comment by JeffLIrion** [comment]
Can you submit it to this branch instead: https://github.com/JeffLIrion/python-androidtv/tree/improved-current-app

**Pull request closed without merging**
