### PR TITLE
Fix netflix continue watching to report paused state

### PR DESCRIPTION
**Pull request by glassbase**
Netflix updated their app sometime around end of December and at the “continue watching” screen, media_session_state stays at value 3 and therefore HA state stays at playing. Before this Netflix update, this would go to media_session_state = 2 and HA would report state paused. 

I used to use this playing to paused state change in an automation for my disabled daughter to catch when her show paused and required us to hit ok to continue watching.

### CODE REVIEW

**Comment by glassbase** [comment]
Here is my notes on Netflix GET_PROPERTIES if you see a better way to handle this

netflix playing:
{'screen_on': True, 'awake': True, 'audio_state': 'playing', 'wake_lock_size': 4, 'current_app': 'com.netflix.ninja', 'media_session_state': 3, 'audio_output_device': 'hdmi', 'is_volume_muted': False, 'volume': 14, 'running_apps': ['STREAM_NOTIFICATION:', 'com.google.android.inputmethod.japanese', 'com.google.android.webview:webview_service', 'com.android.systemui', 'com.google.android.apps.inputmethod.hindi', 'com.google.android.gms.persistent', 'com.google.android.katniss:interactor', 'com.xiaomi.android.tvsetup.partnercustomizer', 'com.google.android.tvrecommendations', 'com.google.android.tvlauncher', 'com.android.providers.tv', 'com.google.process.gapps', 'com.google.android.katniss:search', 'com.google.android.gms', 'com.plexapp.android', 'com.netflix.ninja', 'eu.thedarken.wldonate', 'com.google.android.apps.mediashell', 'com.google.android.gms.unstable', 'com.google.android.tv', 'com.google.android.tv.remote.service', 'com.dazn', 'com.quickplay.android.bellmediaplayer']}

netflix continue watching:
{'screen_on': True, 'awake': True, 'audio_state': 'idle', 'wake_lock_size': 2, 'current_app': 'com.netflix.ninja', 'media_session_state': 3, 'audio_output_device': 'hdmi', 'is_volume_muted': False, 'volume': 14, 'running_apps': ['STREAM_NOTIFICATION:', 'com.google.android.webview:webview_service', 'com.google.android.apps.mediashell:privileged_process0', 'com.google.android.partnersetup', 'com.android.systemui', 'com.google.android.apps.inputmethod.hindi', 'com.google.android.gms.persistent', 'com.google.android.katniss:interactor', 'com.xiaomi.android.tvsetup.partnercustomizer', 'com.google.android.tvrecommendations', 'com.google.android.tvlauncher', 'com.android.providers.tv', 'com.google.process.gapps', 'com.google.android.katniss:search', 'com.google.android.gms', 'com.plexapp.android', 'com.netflix.ninja', 'eu.thedarken.wldonate', 'com.google.android.apps.mediashell', 'com.google.android.tv', 'com.google.android.tv.remote.service', 'com.dazn', 'com.quickplay.android.bellmediaplayer']}

netflix paused:
{'screen_on': True, 'awake': True, 'audio_state': 'paused', 'wake_lock_size': 2, 'current_app': 'com.netflix.ninja', 'media_session_state': 2, 'audio_output_device': 'hdmi', 'is_volume_muted': False, 'volume': 14, 'running_apps': ['STREAM_NOTIFICATION:', 'com.google.android.webview:webview_service', 'com.google.android.apps.mediashell:privileged_process0', 'com.google.android.partnersetup', 'com.android.systemui', 'com.google.android.apps.inputmethod.hindi', 'com.google.android.gms.persistent', 'com.google.android.katniss:interactor', 'com.xiaomi.android.tvsetup.partnercustomizer', 'com.google.android.tvrecommendations', 'com.google.android.tvlauncher', 'com.android.providers.tv', 'com.google.process.gapps', 'com.google.android.katniss:search', 'com.google.android.gms', 'com.plexapp.android', 'com.netflix.ninja', 'eu.thedarken.wldonate', 'com.google.android.apps.mediashell', 'com.google.android.tv', 'com.google.android.tv.remote.service', 'com.dazn', 'com.quickplay.android.bellmediaplayer']}

netflix menu:
{'screen_on': True, 'awake': True, 'audio_state': 'idle', 'wake_lock_size': 2, 'current_app': 'com.netflix.ninja', 'media_session_state': 1, 'audio_output_device': 'hdmi', 'is_volume_muted': False, 'volume': 14, 'running_apps': ['STREAM_NOTIFICATION:', 'com.google.android.webview:webview_service', 'com.google.android.apps.mediashell:privileged_process0', 'com.google.android.partnersetup', 'com.android.systemui', 'com.google.android.apps.inputmethod.hindi', 'com.google.android.gms.persistent', 'com.google.android.katniss:interactor', 'com.xiaomi.android.tvsetup.partnercustomizer', 'com.google.android.tvrecommendations', 'com.google.android.tvlauncher', 'com.android.providers.tv', 'com.google.process.gapps', 'com.google.android.katniss:search', 'com.google.android.gms', 'com.plexapp.android', 'com.netflix.ninja', 'eu.thedarken.wldonate', 'com.google.android.apps.mediashell', 'com.google.android.tv', 'com.google.android.tv.remote.service', 'com.dazn', 'com.quickplay.android.bellmediaplayer']}

**Comment by JeffLIrion** [comment]
The change looks fine, but you'll need to update the tests so that they pass and the coverage stays at 100%. 

https://github.com/JeffLIrion/python-androidtv/blob/288200c018ceb0b073518530b470974c1050af3e/tests/test_androidtv.py#L966-L974

**Comment by JeffLIrion** [comment]
BTW, before this pull request gets merged and the version gets bumped in HA, you should be able to accomplish this via custom state detection rules. It should be something like:

```yaml
media_player:
  - platform: androidtv
    name: Android TV
    device_class: androidtv
    host: 192.168.0.222
    adbkey: "/config/android/adbkey"
    exclude_unnamed_apps: true
    state_detection_rules:
      'com.netflix.ninja':
        - 'paused':
            'media_session_state': 3  # this indentation is important!
            'audio_state': 'idle'  # this indentation is important!
        - 'playing':
            'media_session_state': 3  # this indentation is important!
        - 'standby'
```

**Comment by JeffLIrion** [comment]
I'll merge this once the tests are fixed.

**Pull request closed without merging**
